### ISSUE TITLE
Missed files in new docker image (10.3 version)

### ISSUE THREAD

**Issue by Messering** [nehemiahj/SCScheduledPublishing#15]
Hi @nehemiahj thanks for the SC module, really cool to see how it easily sets schedule publishing with your solution, but with the latest docker image, it seems a few files were missed - ZZ_ScheduledPublishControl.config and files from this directory src/Foundation/ScheduledPublish/code/sitecore/shell/Applications/Content Manager/Dialogs.
I would like to know if there are any plans to fix this, thanks in advance

**Comment by nehemiahj** [comment]
Will update the image today.

**Comment by nehemiahj** [comment]
Republished the docker image for 10.3 and updated with IAR support.

`docker pull nehemiah/sitecore-scheduled-publish:10.3-1809`
 
[https://hub.docker.com/layers/nehemiah/sitecore-scheduled-publish/10.3-1809/images/sha256-8929a5365d45e88d0d777880447fc1a683eed91d9c503ff82eedf92f9e7a06ed?context=explore](https://hub.docker.com/layers/nehemiah/sitecore-scheduled-publish/10.3-1809/images/sha256-8929a5365d45e88d0d777880447fc1a683eed91d9c503ff82eedf92f9e7a06ed?context=explore)
